### ISSUE TITLE
smtcomp mode and define-fun

### ISSUE THREAD

**Issue by dde-cls** [vprover/vampire#105]
_I am not sure this is the right channel for "outsiders" to report issues with Vampire._

I have tried to use Vampire 4.2.2 on a file in SMTLIB2 syntax containing the following line:
```
(define-fun |def_B definitions_0| () Bool (and (forall ( (x_4 Int) ) (=> (and (<= 0 x_4) (<= x_4 MaxInt)) (and (>= x_4 0) (<= x_4 MaxInt)))) (forall ( (x_3 Int) ) (=> (and (>= x_3 0) (<= x_3 MaxInt)) (and (<= 0 x_3) (<= x_3 MaxInt))))))
```

Vampire 4.2.2 seems unable to handle the `define-fun` keyword while the binary used in SMT-COMP 2019 does.

Here is the output produced by 4.2.2:
```
ddeharbe@amsterdam:~/metrics/vampire-4.4-smtcomp-wrapped-sq/bin$ ~/bin/vampire4.2.2 --ignore_missing on --mode smtcomp ../../0008/dcg_cst_i_0_0.p.smt
% Exception at proof search level
User error: list expected: |def_B definitions_0|
```
Here is the output produced by the vampire binary available from Star-Exec:
```
ddeharbe@amsterdam:~/metrics/vampire-4.4-smtcomp-wrapped-sq/bin$ ./vampire --ignore_missing on --mode smtcomp ../../0008/dcg_cst_i_0_0.p.smt
unsat
```
For reference, the description of this binary is
```
This is vampire in git version 82ff932670d944eac2fc4e01926500f781f14961 linked against z3 4.8.4
```

It would be nice that the official release of Vampire matches the capabilities of the version used for SMTCOMP.

**Comment by quickbeam123** [comment]
Dear dde-cls,

this might a be the right channel, but it's hard to debug your problem with just a single line without the context. Could you please provide an ideally minimal example leading to the error?

Also, unfortunately, we don't have the resources to maintain older versions of to the prover. However, if the problems persist with the current version available via the master branch (and versioned as 4.4.0 since 2019-08-12) we will be happy to have a look.

**Comment by selig** [comment]
I believe this is my fault. I have failed to keep this page

https://vprover.github.io/download.html

up to date with binaries. The binary available there is now a few years old and does not fully support SMT-LIB.

I am away from work at the moment but will ensure this is addressed next week.

Cheers, Giles

On 12 Mar 2020, at 17:51, Martin Suda <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear dde-cls,

this might a be the right channel, but it's hard to debug your problem with just a single line without the context. Could you please provide an ideally minimal example leading to the error?

Also, unfortunately, we don't have the resources to maintain older versions of to the prover. However, if the problems persist with the current version available via the master branch (and versioned as 4.4.0 since 2019-08-12) we will be happy to have a look.

**Comment by dde-cls** [comment]
@selig and @quickbeam123, thank you for your prompt replies. I think the issue will be solved with the newest binaries. Meanwhile, I may attempt to compile version 4.4.0.

Best regards, David.

**Comment by dde-cls** [comment]
I confirm that version 4.4.0 fixed this issue, so I close it.
