### ISSUE TITLE
Source of Non-determinism in Vampire

### ISSUE THREAD

**Issue by ibnyusuf** [vprover/vampire#125]
The following code occurs in `TautologyDeletionISE`:

```
int TautologyDeletionISE::compare(Literal* l1,Literal* l2)
{
  CALL("TautologyDeletionISE::compare");

  unsigned f1 = l1->functor();
  unsigned f2 = l2->functor();
  if (f1 < f2) {
    return -1;
  }
  if (f1 > f2) {
    return 1;
  }
  TermList* ts1 = l1->args();
  TermList* ts2 = l2->args();
  while (! ts1->isEmpty()) {
    unsigned c1 = ts1->content();
    unsigned c2 = ts2->content();
    if (c1 < c2) {
      return -1;
    }
    if (c1 > c2) {
      return 1;
    }
    ts1 = ts1->next();
    ts2 = ts2->next();
  }
  return 0;
} // Tautology::compare
```

Because it compares the raw contents of terms it is non-deterministic. Because `TautologyDeletionISE` makes many calls to `Random::getInteger` this non-determinism can and does lead to non-determinism in other parts of the code.

**Comment by selig** [comment]
@quicquid what do you think - I wonder if a better fix would be to make quick sort use a mid pivot instead of a random pivot. It seems unlikely this will impact performance of the sorting too much (there are typically a small number of literals) compared to comparison that looks inside arguments. This would remove the non-determinism produced by interaction with Random.

**Comment by quicquid** [comment]
I also would not expect that the choice of a particular pivot plays much of a choice. Do I understand it correctly that the main impact of the non-determinism is due to the unpredictable order of the literals in the clause (which might influence literals selection)? The comparison of functors feels unproblematic to me (I believe the order of functors is stable under reruns) which would leave the comparison of tsX->content() - under the custom allocator that would have amounted to some kind of age of the clause; under the standard c++ allocator that we currently use, I don't have a good intuition yet.

**Comment by selig** [comment]
My understanding is the non-determinism comes from the number of calls to getInteger in quicksort, hence getting a different sequence of random integers elsewhere (e.g. when flushing the AVATAR model).

**Comment by ibnyusuf** [comment]
> I also would not expect that the choice of a particular pivot plays much of a role. Do I understand it correctly that the main impact of the non-determinism is due to the unpredictable order of the literals in the clause (which might influence literals selection)?
> 
> The comparison of functors feels unproblematic to me (I believe the order of functors is stable under reruns) which would leave the comparison of tsX->content(). Under the custom allocator that would have amounted to some kind of global age of the clause; under the standard c++ allocator that we currently use, I don't have a good intuition yet.

I am not sure whether this 'bug' occurs with standard c++ allocator. I have noticed this behavior on `polymorphic_vampire` branch which still uses the custom allocator. 

@selig that is correct. To clarify it appears that we can have `TermLists*` `ts1` and `ts2` such that `ts1->contents() > ts2->contents()` if running with `--decode` but the other way round if running as part of a schedule.

![image](https://user-images.githubusercontent.com/32095361/84605644-d465f300-ae96-11ea-835c-9bbe554b2b3c.png)

**Comment by quicquid** [comment]
> > I also would not expect that the choice of a particular pivot plays much of a role. Do I understand it correctly that the main impact of the non-determinism is due to the unpredictable order of the literals in the clause (which might influence literals selection)?
> > The comparison of functors feels unproblematic to me (I believe the order of functors is stable under reruns) which would leave the comparison of tsX->content(). Under the custom allocator that would have amounted to some kind of global age of the clause; under the standard c++ allocator that we currently use, I don't have a good intuition yet.
> 
> I am not sure whether this 'bug' occurs with standard c++ allocator. I have noticed this behavior on `polymorphic_vampire` branch which still uses the custom allocator.
> 
> @selig that is correct. To clarify it appears that we can have `TermLists*` `ts1` and `ts2` such that `ts1->contents() > ts2->contents()` if running with `--decode` but the other way round if running as part of a schedule.
> 
> ![image](https://user-images.githubusercontent.com/32095361/84605644-d465f300-ae96-11ea-835c-9bbe554b2b3c.png)

Oh right, different schedules most likely create literals in a different order and it might not be stable under reruns with the same schedule due to jitter in the timer of the scheduler. I presume that with a naive comparison of the whole term the issue would go away and that we consider the implemented term orders too expensive? Then a possible approach might be to use other knowledge of the literal (depth, weight etc. - the hash uses the head symbol and arity which would already agree in this case) to avoid a deep comparison as often as we can and just fall back when necessary.

I also just realized that due to the jitter, the order of skolem functions introduced during proof search might not be stable under reruns. The effect might be small enough to live with it though.

**Comment by quickbeam123** [comment]
Hi, I think we need two fixes! 
1) not to compare the raw content here (we now have 
  `unsigned Term::getId() const` for this)
2) make sure we reset random seed after spawning the child process when we run schedules - this is a bit tricky because a) Setting a seed could be part of a strat's option string and a seed value could be a forced_option. We should agree on what this means. b) because of Random::getBit(), Random's seed is not fully determining the state of the Random module. One should, e.g., reset _remainingBits when Random::setSeed is called.

I happy to implement both in master soonish and expose them as a pull request.

**Comment by quicquid** [comment]
I'm not sure what kind of stability we are aiming for - just under reruns with the same schedule or reruns with different schedules as well? The way I understand `getId()` we would get the first but not the second kind.

**Comment by quickbeam123** [comment]
Actually, I am taking back my 2). As long as we don't encode seeds into the strategies (and their decode strings), which we currently don't, setting the seed only once (which in vampire happens just after parsing the options), making sure the code does not depend on memory layout (i.e. fixing the `content` problem here), and making sure the execution paths in `mode vampire` and `mode portfolio` are identical with respect to the problem processing AND the random number consumption up to the point the actual strategy is run, should be enough!

Note that since we are forking the child processes to run individual strategies in a portfolio, the random numbers consumed when executing a strategy don't influence a different strategy.

**Comment by selig** [comment]
One issue is that we would like to use a Priority Queue (which is implemented as a skip list, hence uses randomness) to organise the schedules. We don't use this normally but we will be exploring different ways of dynamically reordering strategies in the schedule in the future. This means that ensuring that the execution paths in mode vampire and mode portfolio are identical wrt random number consumption seems too restrictive. Although I suppose we could use a heap for the PQ instead.

I don't think we use random during parsing, do we use it in normalisation?

Wrt to the kind of stability we want - we want a strategy running via decode to behave in the same way (modulo lrs non-determinism) as when run in a schedule.

**Comment by ibnyusuf** [comment]
>  and making sure the execution paths in `mode vampire` and `mode portfolio` are identical with respect to the problem processing AND the random number consumption up to the point the actual strategy is run, should be enough!

At the moment, this is not the case. `mode portfolio` has additional random consumption before forking occurs. I have a comment in Slack with regards to this. 

The extra consumption of random bits comes from `PriorityQueue` of strategies that is maintained in `ScheduleExecutor`. In my branch, I have replaced the queue with a stack since it is never used as a priority queue. However, this is far from ideal since we may wish to use it as a priority queue in the future.

**Comment by quickbeam123** [comment]
OK, I see! Let's move to Slack then to finish this off!
