### ISSUE TITLE
Assertion violation at ./Lib/DHMap.hpp:244 (fmb)

### ISSUE THREAD

**Issue by rainoftime** [vprover/vampire#131]
Hi, fo this formula
~~~~
(set-logic LIA)
(declare-const i12 Int)
(declare-const v16 Bool)
(assert (=> v16 v16))
~~~~

vampire 61a2a24
~~~~
The problem is propositional so there are no sorts!
Condition in file ./Lib/DHMap.hpp, line 244 violated:
e
----- stack dump -----
Version : Vampire 4.5.1 (commit 8ca2407 on 2020-07-30 19:28:11 +0800)
Control points passed: 25306
last control point:
        -DHMap::findEntry (25306)
main
 vampireMode()

~  doProving()
   ProvingHelper::runVampireSaturation
    ProvingHelper::runVampireSaturationImpl
     MainLoop::run
      FiniteModelBuilder::init
       SortInference::doInference
----- end of stack dump -----
~~~~

**Comment by selig** [comment]
Finite model building should stop with a user error before getting to this stage as it doesn't work with integers (currently). I'll fix the check.

**Comment by selig** [comment]
Apologies, my mistake. We should be able to handle it as the integer constant isn't used in the problem at all... and of course, there are cases where it is handled that we should be able to handle as well but I'm ignoring those for now.

The issue was that Vampire was assuming that if a sort had some function symbols with it as a return sort then at least one of those function symbols would appear in the problem. An obviously wrong assumption.

I just pushed a fix to master that should fix that but it has one outstanding issue - it won't include the unused function symbol in the model at the end.
