### ISSUE TITLE
Assertion violation at FMB/FiniteModelBuilder.cpp, line 886 (fmb)

### ISSUE THREAD

**Issue by rainoftime** [vprover/vampire#134]
~~~~
(set-logic UF)
(declare-sort S0 0)
(assert (or (forall ((q9 S0) (q10 S0)) (not (distinct q10 q9 q9))) (exists ((q9 S0) (q10 S0)) (not (distinct q9 q9 q10 q10 q9)))))
~~~~
vampire 61a2a24
~~~~
Condition (*csig)[var1] == (*csig)[var2] in file FMB/FiniteModelBuilder.cpp, line 886 was violated, as:
(*csig)[var1] == 2
(*csig)[var2] == 1
----- stack dump -----
Version : Vampire 4.5.1 (commit 8ca2407 on 2020-07-30 19:28:11 +0800)
Control points passed: 118313
last control point:
       -DArray::operator[] (118313)
main
 vampireMode()
  doProving()
   ProvingHelper::runVampireSaturation
    ProvingHelper::runVampireSaturationImpl
     MainLoop::run
      FiniteModelBuilder::init
----- end of stack dump -----
~~~~

**Comment by selig** [comment]
This is fixed by upcoming PR:  https://github.com/vprover/vampire/pull/305

It was an interesting bug that was triggered by the order in which we process variable equalities when assigning subsorts. Note that a  two-variable equality doesn't give any sort information so we infer it  (where possible) from context.  The issue was when we had something like "X0 = X1  | X1 = X2 | p(X2)" - we only know the sort of X0  from that of X1 so the order in which we process the variable equalities matters.
