### ISSUE TITLE
-qa answer_literal causes odd behavior

### ISSUE THREAD

**Issue by apease** [vprover/vampire#310]
Sorry if this is a known and intentional behavior.  While trying different queries, i created the following statement
fof(query_0,conjecture,(( ( ? [V__X] : (s__located(s__John,s__JohnsHouse) ) ) ))).
It didn't generate a syntax error, although the quantifier is superfluous.  That's ok, but when run with the option -qa answer_literal , what is a quick proof without that option isn't found (at least for the 400+ seconds I tried it), and each strategy seems to be given tiny fractions of a second.  I used

/home/apease/workspace/vampire/vampire --avatar off -qa answer_literal --mode casc --proof tptp -t 600 ~/.sigmakee/KBs/temp-comb.tptp

but a proof is found in 1.5 seconds with

/home/apease/workspace/vampire/vampire --avatar off --mode casc --proof tptp -t 600 ~/.sigmakee/KBs/temp-comb.tptp

I tried this first on a version of vampire I compiled this  spring
Apr  5  2020 vampire_rel_master_4147
but just did a git pull and make on the latest 
Jan 12 21:07 vampire_rel_master_5992

and I get the same behavior on both versions.  I know this is an odd case, but trapping it might help save someone time in the future. I'm enclosing the .tptp file 
[temp-comb.zip](https://github.com/vprover/vampire/files/7860103/temp-comb.zip)

**Comment by selig** [comment]
It's known but not exactly intentional. Vampire is confused by the fact that `V_X` doesn't appear in the 'question'. In my local version of Vampire this leads to a segfault (oops).

When running with `-qa answer_literal` vampire will changes the problem from `Axioms |= ?[X].C[X]` to `Axioms, ![X] : (C[X] => ans(X)] |=  ?[X]. ans(X)` for some fresh `ans` predicate. We then run Vampire on `Axioms, ![X] : (C[X] => ans(X)]` looking for ground instances of `ans(X)` as these contain "answers".

Vampire was failing the the variables in the quantifier list didn't match those in the query formula. I just pushed a change to `master` to fix that. Does it work now?

**Comment by apease** [comment]
thanks!  Yes it works with the latest vampire
Jan 13 21:03 vampire_rel_master_5992
I get identical behavior with and without -qa answer_literal .  Vampire provides the solution in about 1.5 sec.  Many thanks!

**Comment by selig** [comment]
Thanks for helping us improve Vampire ;)
