### ISSUE TITLE
Equality Proxy for fof problems

### ISSUE THREAD

**Issue by ibnyusuf** [vprover/vampire#339]
Thanks to Geoff Sutcliffe for raising the following issue

Currently, the default is that we add a single polymorphic equality proxy predicate. This works fine except for `fof` in which case we itnroduce types into an untyped problem. This causes issues for proof parsing.

One solution is to fall back to the monomorphic equality proxy if the problem is `fof`. Any other suggestions?

Another thought, is that we output a `tff` proof even if the problem is `fof`. I am not sure whether the TPTP standard allows this or not.

**Comment by selig** [comment]
The hard path is to post-process the proof to remove the polymorphism. I'm not suggesting this path but it's clearly possible. 

My suggestion would be

(i) output a tff proof if the proof contains types even if the input is fof
(ii) in CASC mode if the problem is fof fall back to monomorphic equality proxy if Geoff isn't happy with a tff proof

A friendly thing would be to add a warning print line that due to X option not being set they're getting a tff proof for a fof problem, allowing a user to add the option if they don't want that.

**Comment by ibnyusuf** [comment]
Response from Geoff:

> would it be acceptable to output a tff proof for a fof problem?

Sure, provided that the leaves of the refutation are the FOF formulae from
the problem (not converted to TFF).

**Comment by easychair** [comment]
The easiest would be to treat equality proxy exactly as equality, that is,
make it polymorphic.

This causes one problem though. For equality, we can always derive its type
from the context. With the equality proxy, we may have a truly polymorphic
axiom E(x,y) -> x = y, which then should be treated in a special way.

For the proof output, I don't quite see the problem. Is it coming from the
fact that Geoff's proof format does not allow polymorphic symbols?

Andrei
