### ISSUE TITLE
Hard simple proof: existence of sqrt(2)

### ISSUE THREAD

**Issue by Celelibi** [vprover/vampire#340]
Hello,
It looks like the proof of anything having to do with sqrt is harder than it should.

    tff(query, conjecture, ?[X: $real]: $product(X, X) = 4.0).

It takes quite some time for the `casc_sat` mode to solve, and the proof is quite complicated. Solving `x*x = 9` takes even more time, but does so by finally enabling theory instantiation. Which, if I understand correctly, just let Z3 deal with it.

However, it looks like Z3 just barf when trying to solve `x*x = 2` and vampire doesn't find a solution within 300 seconds.

**Comment by selig** [comment]
The simple answer here is that you're using the wrong mode. `casc_sat` is intended for when you think the problem is satisfiable. It's surprising that `casc_sat` solved this problem at all as it shouldn't have any theory reasoning capability at all (we never expect theory problems to be satisfiable).

This problem is unsatisfiable. Using `casc` mode I get the immediate proof

```
tff(func_def_13, type, '$inst1': $real).
tff(f24,plain,(
  $false),
  inference(interpreted_simplification,[],[f23])).
tff(f23,plain,(
  4.0 != $product(-2.0,-2.0)),
  inference(instantiation,[],[f21])).
tff(f21,plain,(
  ( ! [X0 : $real] : ($product(X0,X0) != 4.0) )),
  inference(cnf_transformation,[],[f20])).
tff(f20,plain,(
  ! [X0 : $real] : $product(X0,X0) != 4.0),
  inference(ennf_transformation,[],[f2])).
tff(f2,negated_conjecture,(
  ~? [X0 : $real] : $product(X0,X0) = 4.0),
  inference(negated_conjecture,[],[f1])).
tff(f1,conjecture,(
  ? [X0 : $real] : $product(X0,X0) = 4.0),
  file('p',query)).
```

To follow up on "Which, if I understand correctly, just let Z3 deal with it". This isn't quite true. We use Z3 to find instances but we pose a different problem - we ask Z3 if x*x=4 has a model and when it returns x=-2 we use this to create an instance that allows us to disprove the negated conjecture.

**Comment by selig** [comment]
But I agree that we're not going to help  with

`tff(query, conjecture, ?[X: $real]: $product(X, X) = 2.0).`

as Z3 can't give us a rational X such that X*X =  2.0 - we can only instantiate with things that are rational.

**Comment by Celelibi** [comment]
I understand that Z3 can deal with irrational numbers.
```smt
(declare-const x Real)
(assert (= 2.0 (* x x)))
(check-sat)
(get-model)
```
I have however no idea how this could integrate with Vampire, if at all.
I guess you can close this issue if there's nothing to be done there.

**Comment by selig** [comment]
I just checked and the object (for x in the above) I get back from the model (via the z3 api) is `(root-obj (+ (^ x 2) (- 2)) 2)` i.e. an algebriac number. I don't think we'll be handling algebriac numbers natively (in Vampire) soon.

Interstingly, CVC4 returns

`(define-fun x () Real (witness ((BOUND_VARIABLE_822 Real)) (and (>= BOUND_VARIABLE_822 (/ (- 1482917) 1048576)) (>= (* (- 1) BOUND_VARIABLE_822) (/ 741455 524288)))))`

which is roughly the same amount of cryptic but clearly different.
