### ISSUE TITLE
Finite model finding fails with unreasonable incompleteness

### ISSUE THREAD

**Issue by Columpio** [vprover/vampire#348]
On the following problem: [prop_16.txt](https://github.com/vprover/vampire/files/8429652/prop_16.txt) I obtain the following:

1. For `vampire -sa fmb -av off --input_syntax smtlib2 -fmbes sbeam prop_16.txt`:
    `Cannot enumerate next child to try in an incomplete setup`
2. For `vampire -sa fmb -av off --input_syntax smtlib2 -fmbes smt prop_16.txt`:
    `Cannot represent all propositional literals internally`
3. For `vampire -sa fmb -av off --input_syntax smtlib2 -fmbes contour prop_16.txt`:
    ```
    % Refutation found. Thanks to Tanya!
    % SZS status Unsatisfiable for prop_16
    % SZS output start Proof for prop_16
    791. $false [finite model not found]
    % SZS output end Proof for prop_16
    ```

First two runs also report `incomplete strategy`.

I can reproduce such a behaviour both on master (884a27a7531e1868b8eb89f3e40fb09daa26a9ca) and on #346.
Output of 3. (`contour`) seems to be the same as in #303.
Both `cvc --finite-model-find` and `z3` diverge on this problem (but without any failure or `unsat` answer in a reasonable time).

**Comment by quickbeam123** [comment]
Hi Yurii, 

prop_16.txt is most likely unsatisfiable (`--decode lrs+1011_2:1_av=off:irw=on:lwlo=on:nm=16:newcnf=on:nwc=2:sd=4:ss=axioms:st=3.0:sp=occurrence_300` gives a refutation in under 20s here) so none of the cases you report are unreasonable (although I am only getting `Cannot represent all propositional literals internally` for all three).

`Cannot enumerate next child to try in an incomplete setup` could probably be improved as a message, but what is meant is an incomplete domain size enumeration setup. Vampire knows it cannot look for other models, but it's not sure it didn't skip some.

`Refutation found.` is a reasonable (although rare) answer even under fmb.

**Comment by Columpio** [comment]
@quickbeam123 I think this contradicts the documentation
--fmb_enumeration_strategy (-fmbes)
        How model sizes assignments are enumerated in the multi-sorted setting. 
        (Only smt and contour are known to be **finite model complete** and can therefore 
        return UNSAT.)
That is, `smt` and `contour` should **not** return `incomplete` ever.
In case it is not right, at least documentation should be fixed, I think.

**Comment by quickbeam123** [comment]
But didn't you get `incomplete setup` from `sbeam` only, a refutation from `contour` and `Cannot represent all propositional literals internally` from `smt`? The last is basically a polite version of an out-of-memory exception, not a "gave up" due to incompleteness. 

I agree the documentation could be more detailed!

**Comment by quickbeam123** [comment]
We don't expose any details of FMB refutations as most of that information is hidden inside the internal SAT solver (and would be a huge unreadable mess anyway, only meaningful through the lens of a relatively complicated SAT encoding). But FMB refutations are valid in principle. The best way to make sure another bug is not showing up is to rerun vampire in saturating mode (I ran `--mode casc` on prop_16.txt yesterday).

Ad "OOM": I should have been more precise. This will not get fixed by increasing the `--memory_limit`. What "Cannot represent literals" actually means is that the SAT encoding would like to introduce more variables than we can represent in minisat. This is fixed by the 32bit representation at around 2 billion and cannot be easily extended.

These are the limits of the FMB technology as implemented in Vampire.

**Comment by Columpio** [comment]
@quickbeam123 Thank you for the clarification.
So, is there any chance to increase the representation size? For example, by rebuilding minisat with 64bit?

**Comment by quickbeam123** [comment]
64bit minisat would not be easy. Minisat relies relatively heavily on bit twiddling and, maybe even more importantly, part of minisat's effieciency lies in its compact memory footprint which would essentially double with 64 bit variables...

However, if you have any control of your problem's encoding into FOL, you could try avoiding predicates and functions of large arities (number of arguments).

In prop_16.txt the main culprit is probably:
```(declare-fun deltapat_4 (adtConstr_0 adtConstr_0 adtConstr_0 adtConstr_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0 State_0) State_0)```

Note that we need
n^4*m^17 propositional variables to deal with it, where n is the domain size of adtConstr_0 and m the domain size of State_0. This will be too much to represent already for n=2 and m=3.

**Comment by Columpio** [comment]
I close this issue because the problem appears because of the *intentional* limitation in Vampire's finite-model building engine.
That is, if the problem has functions with large arities (> 20 arguments), Vampire cannot calculate the result as it's internal encoding to SAT is exponential.

I suggest to add this clarification to error messages from the issue post as well as a recommendation to reduce function arities.
