### ISSUE TITLE
Vampire zip download make warning

### ISSUE THREAD

**Issue by daviddamestani** [vprover/vampire#68]
When downloading Vampire from Github and doing:

make vampire

the first line to the terminal is

fatal: not a git repository (or any of the parent directories): .git

**Comment by selig** [comment]
Good point - the current Makefile uses git information to produce Version information.

We are currently creating an alternative CMake file that will not have this dependency (therefore I do not want to update the current Makefile). 

To make it 'work' you can hack the Makefile but I would recommend cloning the project from git rather than downloading the zipped repository.

**Comment by quickbeam123** [comment]
I think this will only be a problem for "make vampire_dbg" / "make vampire_rel" / etc ... not "make vampire" but yes, cloning from git (instead of downloading zip file) should "fix this".

**Comment by selig** [comment]
I'm adding a point to our README about how to compile if downloading zip file and closing.
