### ISSUE TITLE
large proof for simple resolution

### ISSUE THREAD

**Issue by apease** [vprover/vampire#76]
Instead of reporting a proof of contradiction that should take just a few steps, it uses thousands with a massive avatar_sat_refutation step at the end .
  The basic proof is about the rule "people can't have an average work week more than 70.0 hours" and uses three statements -

tff(f325,axiom,(
  ! [X327,X130 : $real] : (s__instance(X327,s__Human) => (s__avgWorkHours__2Re(X327,X130) => $less(X130,70.0)))),
  file('/home/apease/.sigmakee/KBs/SUMO.tff',kb_SUMO_325)).

tff(f743,axiom,(
  s__avgWorkHours__2Re(s__Human0,80.0)),
  file('/home/apease/.sigmakee/KBs/SUMO.tff',kb_SUMO_743)).

tff(f1297,axiom,(
  s__instance(s__Human0,s__Human)),
  file('/home/apease/.sigmakee/KBs/SUMO.tff',kb_SUMO_1297)).

I executed with -

./vampire --mode casc -t 300 SUMO.tff

//vampire --version
Vampire 4.2.2 (commit 552c234 on 2018-07-02 14:53:33 +0100)

So, Vampire is correctly finding the contradiction, but reporting a decidedly non-minimal proof.  Have I just used the wrong mode or option?

[infout-huge.zip](https://github.com/vprover/vampire/files/3318018/infout-huge.zip)
[SUMO.zip](https://github.com/vprover/vampire/files/3318019/SUMO.zip)

**Comment by arademaker** [comment]
Hi @apease , could you provide the command line that you used? I would like to try to reproduce the error.

**Comment by apease** [comment]
listed above -

./vampire --mode casc -t 300 SUMO.tff

**Comment by apease** [comment]
avatar_sat_refutation is just an identifier in the resulting proof, which I may be misunderstanding

**Comment by apease** [comment]
aha just a version issue - this must have been fixed between 7/2/2018 and 7/19/2018 sorry for the trouble

....
tff(f15758,plain,(
  $false),
  inference(subsumption_resolution,[],[f15757,f10054])).
% SZS output end Proof for SUMO
% ------------------------------
% Version: Vampire 4.2.2 (commit 6588b35 on 2018-07-19 13:39:17 +0200)
% Termination reason: Refutation

% Memory used [KB]: 23283
% Time elapsed: 0.149 s
% ------------------------------
% ------------------------------
% Success in time 0.345 s
apease@apease-ThinkPad-T460s:~/workspace/sigmanlp$ /home/apease/workspace/vampire/vampire --version
Vampire 4.2.2 (commit 6588b35 on 2018-07-19 13:39:17 +0200)

**Comment by selig** [comment]
Hi Adam, yep it should have been sorted after the CASC competition in Berlin (when we lost some proofs in the competition as they took too long to print!) but I do think it was temporarily disabled in master by mistake at one point. The master branch definitely has it sorted. For context - the 'issue' is when the proof is found by AVATAR we need to find the 'unsat core' in the SAT solver and use this to prune the proof this sometimes wasn't done at all/properly.

As a side-note, Vampire is tuned for 'quick' proofs rather than 'short' ones and often when we find a proof with AVATAR there exists a shorter one without it. If you want to see if there is a proof without AVATAR that might be shorted you can add "--forced_options av=off" after "--mode casc" and that will make all strategies run without AVATAR.

**Comment by apease** [comment]
cool - thanks!  And sorry again for the outdated bug report
