### ISSUE TITLE
Unnecessary Superposition Inferences?

### ISSUE THREAD

**Issue by ibnyusuf** [vprover/vampire#82]
The following code from EqHelper returns subterms suitable for rewriting by superposition

```
TermIterator EqHelper::getRewritableSubtermIterator(Literal* lit, const Ordering& ord)
{
  CALL("EqHelper::getRewritableSubtermIterator");

//  if (lit->isEquality()) {
//    if (lit->isNegative()) {
//      return TermIterator::getEmpty();
//    }
  if (lit->isEquality() && lit->isPositive()) {
    TermList sel;
    switch(ord.getEqualityArgumentOrder(lit)) {
    case Ordering::INCOMPARABLE:
      {
	NonVariableIterator nvi(lit);
	return getUniquePersistentIteratorFromPtr(&nvi);
      }
    case Ordering::EQUAL:
    case Ordering::GREATER:
    case Ordering::GREATER_EQ:
      sel=*lit->nthArgument(0);
      break;
    case Ordering::LESS:
    case Ordering::LESS_EQ:
      sel=*lit->nthArgument(1);
      break;
#if VDEBUG
    default:
      ASSERTION_VIOLATION;
#endif
    }
    if (!sel.isTerm()) {
      return TermIterator::getEmpty();
    }
    return getUniquePersistentIterator(getConcatenatedIterator(getSingletonIterator(sel),
							       vi(new NonVariableIterator(sel.term()))));
  }

  NonVariableIterator nvi(lit);
  return getUniquePersistentIteratorFromPtr(&nvi);
}
```

As can be seen, if the literal is a negative equality, we return subterms of both the left and right hand side. Theoretically, even with negative equalities, we only need to superpose onto the larger side (see Handbook of Automated Reasoning). Therefore, it seems as though we are returning unnecessary subterms and carrying out unnecessary inferences?

**Comment by easychair** [comment]
Rewriting by unit equalities is a simpification. SImplification inferences
are always good but not necessary (not even in larger part of equalities).
The only issue one should consider in the "apply or not apply" question for
simplifications is the trade-off between what we gain and the time we spend
for applying simplifying inferences.

A

**Comment by ibnyusuf** [comment]
Not sure i've understood. The iterator in question here "getRewritableSubtermIterator" is used in superposition not demodulation.

The problem that I am trying to raise is that we seem to be doing superposition (not rewriting/demodulation) on the smaller side of negative equality literals when the theory doesn't call for this.

**Comment by easychair** [comment]
Dear ibnyusuf,

> Not sure i've understood. The iterator in question here
"getRewritableSubtermIterator" is used in superposition not demodulation.
> The problem that I am trying to raise is that we seem to be doing
superposition (not rewriting/demodulation) on the smaller side of negative
equality literals when the theory doesn't call for this.

This is what you have previously written:

> The following code from EqHelper returns subterms suitable for rewriting
by superposition

Note that you used the term "rewriting".

If your question about backward superposition, I am not sure I have time to
dig in the code but a correct implementation of superposition into negative
equality literals *l != r* should do this:

(1) if *l > r*, then only *l* will be put in the index, so superposition in
*r* will be never applied
(2) if *l* and *r* are incomparable, then both *l* and *r* should be put in
the index, however, if we apply superposition into *r* with a substitution
*s*, we should check that *ls > rs* does not hold, that is, *r* does not
become smaller than *l* after substitution.

For forward superposition, it is similar but instead of *r* not being in
the index, you simply do not apply superposition in it.

Best regards,
Andrei

**Comment by ibnyusuf** [comment]
Hi Andrei, Ahmed here. Thanks for the response.

I am claiming that when *l != r* and *l > r* we still put *r* in the index. Likewise in forward superposition we still carry out superpositions on *r*.

**Comment by easychair** [comment]
Than you, Ahmed. We will check the code. Is it only about negative
equalities or applies to positive ones as well?

Regards,
Andrei

**Comment by ibnyusuf** [comment]
It is only negative equalities. It is linked to the following code:
```
TermIterator EqHelper::getRewritableSubtermIterator(Literal* lit, const Ordering& ord)
{
  CALL("EqHelper::getRewritableSubtermIterator");

//  if (lit->isEquality()) {
//    if (lit->isNegative()) {
//      return TermIterator::getEmpty();
//    }
  if (lit->isEquality() && lit->isPositive()) { ...
```
If we remove the `&& lit->isPositive()` everything should be fine I think.

Regards

**Comment by quickbeam123** [comment]
Hi, I checked the code! Ahmed, you are right, the "isPositive" should be dropped. However, it will not change what clauses Vampire actually derives, because of the second in check in Superposition.cpp:

` if(rwLitS->isEquality()) {
    //check that we're not rewriting only the smaller side of an equality
    TermList arg0=*rwLitS->nthArgument(0);
    TermList arg1=*rwLitS->nthArgument(1);

    if(!arg0.containsSubterm(rwTermS)) {
      if(Ordering::isGorGEorE(ordering.getEqualityArgumentOrder(rwLitS))) {
        return 0;
      }
    } else if(!arg1.containsSubterm(rwTermS)) {
      if(Ordering::isGorGEorE(Ordering::reverse(ordering.getEqualityArgumentOrder(rwLitS)))) {
        return 0;
      }
    }
  }`

I am not checking what effect on performance will it have, not to store the smaller sides of negative equalities in the index and thus skipping some superposition attempts.

If the experiment does not reveal any bug in the above reasoning, I will push the change.

**Comment by ibnyusuf** [comment]
Great, once we do that, can we get rid of the above check in Superposition.cpp? I'd argue that it is flawed anyway. It is possible that 

`if(!arg0.containsSubterm(rwTermS)) `

and 

`if(!arg1.containsSubterm(rwTermS))`

are both false. I.e. both sides of the literal contain `rwTermS` as a subterm. In this case even if the side that we are rewriting is the smaller one, we still carry out the superposition inference.

Regards,
Ahmed

**Comment by quickbeam123** [comment]
Why would you want to get rid of a filter check when you identify it as imperfect?

Do you see an elegant way of strengthening it instead? (We always want as few inferences as possible while preserving completeness.)

**Comment by ibnyusuf** [comment]
My thought process was that once we fix the iterator we will never be rewriting the smaller side, but I now note that the above filter is _after_ the application of the unifier. 

However, it does require some strengthening. I'll get back to you on how I think this ought to be done.

**Comment by quickbeam123** [comment]
Yes, I forgot to stress that. This check comes after the substitution is applied.

Another question is how often will the case arise. We are talking of a situation where the two sides of the equality are incomparable before substitution, but both will contain the subterm being rewritten after the substitution while one becomes larger than the other. Does it even occur at all?

**Comment by ibnyusuf** [comment]
Agreed, seems very unlikely. However, if we could somehow store which side of an equality literal a term comes from and then pass that information to Superposition, it would save one/two calls to 

`arg1.containsSubterm(`

which iterates through the term to find info which we theoretically could already possess.
