### ISSUE TITLE
Proof output

### ISSUE THREAD

**Issue by arademaker** [vprover/vampire#99]
Does Vampire support the PCL2 protocol for proof output?

I would like to use https://www.mankier.com/1/epclextract# t help me understand a large proof.

**Comment by quickbeam123** [comment]
Dear Alexandre, unfortunately Vampire does not support PCL2. However, you can use the option `-p tptp` to have it output the proof in a standardized TPTP format.

**Comment by arademaker** [comment]
Hi @quickbeam123 , thank you for the quick answer. What is the general advice for debug long proofs from Vampire? I am using casc more, so I believe the output is already TPTP (not sure if TPTP is really the same format of input or the TSTP). I remember the Geoff used to provide some graphical tools for inspecting proofs, but I could not find in the TPTP website. I also found #76 that can provide some tips for producing short proofs. Any general advice?

**Comment by quickbeam123** [comment]
Hi Alexandre, casc mode indeed entails TPTP format by default. The graphical tool by Geoff et al. you mean is probably IDV (S. Trac, Y. Puzis, and G. Sutcliffe. An Interactive Derivation Viewer. In S. Autexier and C. Benzmuller, editors, Proceedings of the 7th Workshop on User Interfaces for Theorem Provers, 3rd International Joint Conference on Automated Reasoning, volume 174 of Electronic Notes in Theoretical Computer Science, pages 109–123, 2006.) System on TPTP page (http://www.tptp.org/cgi-bin/SystemOnTPTP) allows you to selected it as one of its "extras", although I don't have any experience using it.

Since you already read #76 you know that Vampire proofs might be sometimes large and hard to read for humans. So it is a bit difficult to give general advice. Could you maybe specify what you mean by debugging proofs? What is it that you would like to achieve and are failing to?

**Comment by gleiss** [comment]
Hi Alexandre, you could also have a look at SatVis, which is a (for now) Vampire-specific tool to visualize saturation runs. We implemented SatVis over the last year, mainly to understand Vampire's behaviour on encodings coming from applications of Vampire to Software Verification. The tool has many similarities to IDV (at least according to the IDV-paper; we couldn't find the IDV-tool online), with a more modern interface.
SatVis focuses on understanding saturation runs (that is, all clauses generated in the run), in contrast to IDV, which only visualizes proofs. It is therefore possible to get more insights with SatVis (inspect the set of passive clauses, visualize runs where no proof is found; interactively perform manual clause selection).

SatVis has some (arguably natural) limits (most of them probably also apply to IDV):
- since we have to parse all events of the saturation run and compute a layout for each clause, there is a certain limit to the scalability of the tool, so it may be the case that the runs you need to visualize are too big. 
- We don't support Avatar, so SatVis enforces Avatar to be turned off using the option `-av off`. Note that it may be the case that Vampire is not able to reproduce the proofs found with Avatar, if one turns off Avatar. 
- We don't support the CASC-mode directly (since we don't think it makes much sense to visualize multiple runs at once). Note that if you are able to find a proof in CASC-mode, you should be able to find the same proof if you run Vampire in the default-mode with the options used by strategy which succeeded in CASC-mode.

You can find a description of how to run the SatVis tool at [github.com/gleiss/saturation-visualization](https://github.com/gleiss/saturation-visualization).
